services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongodb
  reservations:
    image: asia-southeast2-docker.pkg.dev/oceanic-hangout-373706/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: asia-southeast2-docker.pkg.dev/oceanic-hangout-373706/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: asia-southeast2-docker.pkg.dev/oceanic-hangout-373706/payments/production
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: asia-southeast2-docker.pkg.dev/oceanic-hangout-373706/notifications/production
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongodb:
    image: mongo:latest
